version: "Compose specification"
services:
  metro-app:
    build: ./frontend
    ports:
      - 3000:3000
  metro-api:
    build: ./backend
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env
    environment:
      DB_URL: MONGO_URL
  
volumes:
  metroje:
